# Generated by Django 4.0.3 on 2023-07-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_enrollment_submission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='image_submission',
            field=models.FileField(blank=True, null=True, upload_to='submission_images/'),
        ),
    ]
