# Generated by Django 4.0.3 on 2023-07-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_alter_enrollment_image_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
