# Generated by Django 4.0.3 on 2023-07-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0005_alter_hackathon_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='file_submission',
            field=models.FileField(blank=True, default=None, null=True, upload_to='submission_files/'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='image_submission',
            field=models.FileField(blank=True, default=None, null=True, upload_to='submission_images/'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='link_submission',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
