# Generated by Django 4.0.3 on 2023-08-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0010_alter_enrollment_file_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='host_display_name',
            field=models.CharField(default='asd', max_length=50),
        ),
    ]
