# Generated by Django 4.0.3 on 2023-08-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0011_hackathon_host_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='description',
            field=models.TextField(max_length=2048),
        ),
    ]
