# Generated by Django 4.0.3 on 2023-08-05 09:46

import backend.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0012_alter_hackathon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='submission_type',
            field=backend.utils.models.ChoiceArrayField(base_field=models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=32), size=1),
        ),
    ]
