# Generated by Django 4.2.4 on 2023-08-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0014_alter_hackathon_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="description",
            field=models.TextField(max_length=10240),
        ),
    ]
