# Generated by Django 4.2.4 on 2023-08-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0015_alter_hackathon_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="host_display_name",
            field=models.CharField(max_length=50),
        ),
    ]
