# Generated by Django 4.1.7 on 2023-05-05 05:19

import backend.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=backend.utils.models.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("male", "Male"),
                        ("female", "Female"),
                        ("other", "Other"),
                        ("prefer.not.to.say", "Prefer Not To Say"),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=1,
            ),
        ),
    ]
