# Generated by Django 4.0.3 on 2023-07-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_hackathon_user_enrolled_hackathons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
