# Generated by Django 4.0.3 on 2023-07-23 14:37

import backend.utils.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_hackathon_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='file_submission',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='image_submission',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='link_submission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enrolled_hackathons',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='reward',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='submission_type',
            field=backend.utils.models.ChoiceArrayField(base_field=models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=32), blank=True, null=True, size=1),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_submission', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file_submission', models.FileField(blank=True, null=True, upload_to='files/')),
                ('link_submission', models.URLField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hackathon')},
            },
        ),
    ]
