# Generated by Django 4.0.3 on 2023-07-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_hackathon_file_submission_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
