# Generated by Django 4.0.3 on 2023-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='file_submission',
            field=models.FileField(blank=True, null=True, upload_to='submission_files/'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='image_submission',
            field=models.ImageField(blank=True, null=True, upload_to='submission_images/'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
