# Generated by Django 4.0.3 on 2023-07-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_enrollment_file_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
