# Generated by Django 4.0.3 on 2023-07-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_hackathon_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='host',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Hackathon',
        ),
    ]
