# Generated by Django 4.2.4 on 2023-08-11 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_hackathon_host_delete_enrollment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="token_created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
